### ISSUE TITLE
Question about evaluate metric

### ISSUE THREAD

**Issue by WeitaiKang** [ch3cook-fdu/Vote2Cap-DETR#16]
Hi authors,

I am new to this task and want to consult a question about the metric in this 3D dense captioning domain, which is a little bit contradictory after I checked with several papers.

In you paper, the captioning metric is averaged by the number ground truth instance, so it cannot evaluate redundant bbox prediction.  However, in Scan2cap and D3Net, which you put in the same table 1, they will average the captioning metric by the percentage of correct predicted bbox. Therefore, previous related work evaluated the redundant bbox prediction.

Is it unfair of your metric, or am I missing something here? I would really appreciate your help to clarify it out!

**Comment by ch3cook-fdu** [comment]
Starting from the very first work on 3D Dense Captioning, [Scan2Cap](https://arxiv.org/pdf/2212.00836.pdf), the **Recall-only** $m@k$IoU metric has been widely adopted as the only evaluation metric in many existing works, including [D3Net](https://daveredrum.github.io/D3Net/D3Net.pdf), [SpaCap3D](https://arxiv.org/pdf/2204.10688.pdf), and etc. Actually, the F-1 based $m@k$IoU metric you mentioned should be a better way to evaluate the overall performance of 3D Dense Captioning models, However, it is not formally introduced until the [UniT3D](https://arxiv.org/pdf/2212.00836.pdf) paper.

In our paper, all methods are listed and evaluated under the Recall-only $m@k$IoU metric, thus, I believe it should be a **fair** comparison. If you are interested in the F-1 based $m@k$IoU metrics for our method, you can refer to the ScanRefer online [test benchmark](https://kaldir.vc.in.tum.de/scanrefer_benchmark/benchmark_captioning) and read their document for more information.

**Comment by WeitaiKang** [comment]
Great! Thanks for your comprehensive explanation and mentioning those related works. It does help me a lot.
