### ISSUE TITLE
scannet_means.npz and scannet_reference_means.npz

### ISSUE THREAD

**Issue by cy94** [ch3cook-fdu/Vote2Cap-DETR#18]
Hi @ch3cook-fdu thanks for the great work! I was able to reproduce your results on the ScanRefer dataset and now I want to try it on a new dataset. I see that you use 2 mean arrays - `data/scannet/meta_data/scannet_means.npz` and `data/scannet/meta_data/scannet_reference_means.npz` in the model, both with shape `(18, 3)`. Could you let me know how you computed these, and how to do it for a new dataset?

Thanks!
Chandan

**Comment by ch3cook-fdu** [comment]
Thanks for your interest in our work! These `.npz` files are only used for VoteNet. If you are training our Vote2Cap-DETR families, these are not required. Feel free to discard any code that relates to these files.

**Comment by cy94** [comment]
Thanks for the quick response!
