### ISSUE TITLE
What should I do to visualize this data?

### ISSUE THREAD

**Issue by YigaoWang** [ch3cook-fdu/Vote2Cap-DETR#20]
What should I do to visualize this data? Or the pictures in the paper are made by PPT
<img width="294" alt="image" src="https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/62236109/3164ad79-110a-4fe8-bd87-3a6d429926c8">

**Comment by YigaoWang** [comment]
我应该怎么做才能把 caption 和 bbox 展示到一幅图里
<img width="729" alt="image" src="https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/62236109/481dce34-e536-4022-b4c9-c8398e38f8ee">
![image](https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/62236109/b3a350b6-b90c-4162-b1a7-b6620fe20e90)

**Comment by ch3cook-fdu** [comment]
Please refer to https://github.com/ch3cook-fdu/Vote2Cap-DETR/issues/11 for visualization instructions. Sadly, we have not found a good way to visualize both texts and bounding boxes, instead, we manually align these two visualizations in PPT.

**Comment by YigaoWang** [comment]
> Please refer to #11 for visualization instructions. Sadly, we have not found a good way to visualize both texts and bounding boxes, instead, we manually align these two visualizations in PPT.

Thank you very much. Let me try！

**Comment by YigaoWang** [comment]
<img width="890" alt="image" src="https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/62236109/db7fc0eb-4ef1-4f12-af71-3bb82999a492">

OK，I have achieved it. Thanks again!
