### ISSUE TITLE
How to visualize the encoder scene and output bbox

### ISSUE THREAD

**Issue by Believeht029** [ch3cook-fdu/Vote2Cap-DETR#25]
Thanks for your amazing work!
I would like to visualize the encoder scene and the predicted bounding box output, yet I dont know how to do it.
I would really appreciate it if anyone can offer some guidance!

**Comment by ch3cook-fdu** [comment]
Please refer to https://github.com/ch3cook-fdu/Vote2Cap-DETR/issues/11
